"""Hand-pinned per-GT-wall diagnostic -- Track V milestone 2 step 3a, second
diagnostic STOP.

Not a pipeline module. Kills the scale-bootstrap confound in
`score_align.py`'s automatic coarse-match refine (which pools over all
candidate matches, including polluted ones) by fitting the similarity
transform from a small number of *hand-identified, visually verified*
anchor point correspondences only -- picked by inspecting
`out/pin_check_*.png` (generated by `out/_plot_pinning.py`) plus the raw
longest-wall coordinate dump, not assumed. Anchor choices and the visual
reasoning behind them are documented inline per plan.

Frozen once fit (no iterative refine over the full population -- that is
exactly where the pollution re-enters, per Dan's instruction). Applied to
every predicted wall, then every GT wall is individually classified against
the best-matching predicted wall under the *same* cost function
`eval/metrics/matching.py` uses (symmetric mean centerline distance +
overlap ratio), whether or not it clears the Hungarian assignment.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from eval.metrics.matching import _overlap_ratio, _sym_mean_dist, match_walls, plan_diagonal  # noqa: E402
from extraction.trackv.score_align import SimilarityTransform, apply_transform_to_plan  # noqa: E402

PRED_DIR = Path(__file__).parent / "out" / "step3a_predictions"
GT_DIR = REPO_ROOT / "data" / "corpus" / "gt_provisional"
OUT_PATH = Path(__file__).parent / "out" / "step3a_pinned_diagnostic.json"

FT_TO_MM = 304.8


def fit_similarity_umeyama(src_pts: list[tuple[float, float]], dst_pts: list[tuple[float, float]]) -> SimilarityTransform:
    """Least-squares similarity (uniform scale, rotation, translation; no
    reflection) from >=2 point correspondences. Standard Umeyama solution."""
    P = np.asarray(src_pts, dtype=float)
    Q = np.asarray(dst_pts, dtype=float)
    mu_p, mu_q = P.mean(axis=0), Q.mean(axis=0)
    Pc, Qc = P - mu_p, Q - mu_q
    sigma_p2 = (Pc**2).sum() / len(P)
    Sigma = (Qc.T @ Pc) / len(P)
    U, D, Vt = np.linalg.svd(Sigma)
    S = np.eye(2)
    if np.linalg.det(U) * np.linalg.det(Vt) < 0:
        S[1, 1] = -1
    R = U @ S @ Vt
    s = np.trace(np.diag(D) @ S) / sigma_p2
    t = mu_q - s * (R @ mu_p)
    rotation_deg = float(np.degrees(np.arctan2(R[1, 0], R[0, 0])))
    return SimilarityTransform(scale=float(s), rotation_deg=rotation_deg, tx=float(t[0]), ty=float(t[1]))


def fit_residuals(transform: SimilarityTransform, src_pts, dst_pts) -> list[float]:
    return [
        ((transform.apply(p)[0] - q[0]) ** 2 + (transform.apply(p)[1] - q[1]) ** 2) ** 0.5
        for p, q in zip(src_pts, dst_pts)
    ]


def classify_gt_wall(gt_wall: dict, aligned_pred_walls: list[dict], tau: float) -> dict:
    """Best-candidate diagnosis against ALL pred walls, using matching.py's
    own cost primitives directly (not re-implemented)."""
    best = None
    for p in aligned_pred_walls:
        d = _sym_mean_dist(p, gt_wall)
        ov = _overlap_ratio(p, gt_wall)
        if best is None or d < best["residual"]:
            best = {"pred_id": p["id"], "residual": d, "overlap": ov}
    if best is None:
        return {"verdict": "ABSENT", "best_pred_id": None, "residual": None, "overlap": None}

    residual_frac = best["residual"] / plan_diagonal([gt_wall])  # normalized per-wall for readability only
    if best["residual"] >= tau:
        verdict = "ABSENT" if best["residual"] > 3 * tau else "MISPLACED"
    elif best["overlap"] <= 0.8:
        verdict = "FRAGMENTED"
    else:
        verdict = "MATCHED"
    return {
        "verdict": verdict,
        "best_pred_id": best["pred_id"],
        "residual": round(best["residual"], 1),
        "residual_frac_of_tau": round(best["residual"] / tau, 3),
        "overlap": round(best["overlap"], 3),
    }


def run_15x30() -> dict:
    plan_id = "15x30-ft-Best-House-Plan-Model"
    pred = json.loads((PRED_DIR / f"{plan_id}.json").read_text(encoding="utf-8"))
    gt = json.loads((GT_DIR / f"{plan_id}.json").read_text(encoding="utf-8"))
    pw = {w["id"]: w for w in pred["walls"]}

    # Anchors, from out/pin_check_15x30-...png + the raw coordinate dump:
    # W42 (len 1062.8, x~236-246, spans nearly the full pred cluster height)
    # is the ONLY top-3-longest pred wall that sits at a bbox EDGE (left) --
    # visually confirmed the other two top-3 walls (W9, W12) sit in the
    # MIDDLE of a dense hatch tangle, not at any perimeter, and are not
    # used as anchors. Its two endpoints are corners: top-left and
    # bottom-left. A second anchor comes from W43 (len 504.8, x~830-834,
    # the only wall found near the pred bbox's right edge at all), whose
    # lower endpoint (829.5, 1364.0) sits at the same y as W42's lower
    # endpoint (1379.4) -- consistent with both reaching toward the
    # building's bottom edge -- used as a probable bottom-right corner.
    # This is the plan's only pair of independently-plausible anchors;
    # flagged as thinner evidence than 30x50's three-anchor fit.
    src = [
        tuple(pw["W42"]["start"]),  # top-left corner region
        tuple(pw["W42"]["end"]),  # bottom-left corner
        tuple(pw["W43"]["end"]),  # probable bottom-right corner
    ]
    dst = [
        (1932.7, 2475.5),  # GT top-left corner (w_s7/w_s2 junction)
        (2003.7, 11493.5),  # GT bottom-left corner (w_s7/w_s6 junction)
        (6344.7, 11493.3),  # GT bottom-right corner (w_s4/w_s6 junction)
    ]
    transform = fit_similarity_umeyama(src, dst)
    residuals = fit_residuals(transform, src, dst)

    nominal_w, nominal_h = 15 * FT_TO_MM, 30 * FT_TO_MM
    gt_bbox_w = 6362.3 - 1932.7
    gt_bbox_h = 11493.5 - 2475.5
    pred_xs = [c for w in pred["walls"] for c in (w["start"][0], w["end"][0])]
    pred_ys = [c for w in pred["walls"] for c in (w["start"][1], w["end"][1])]
    pred_bbox_w_native = max(pred_xs) - min(pred_xs)
    pred_bbox_h_native = max(pred_ys) - min(pred_ys)
    pinned_implied_w = pred_bbox_w_native * transform.scale
    pinned_implied_h = pred_bbox_h_native * transform.scale

    return _finish(plan_id, pred, gt, transform, residuals, {
        "nominal_mm": [nominal_w, nominal_h],
        "gt_bbox_mm": [round(gt_bbox_w, 1), round(gt_bbox_h, 1)],
        "pred_bbox_native": [round(pred_bbox_w_native, 1), round(pred_bbox_h_native, 1)],
        "pinned_transform_implied_pred_envelope_mm": [round(pinned_implied_w, 1), round(pinned_implied_h, 1)],
    })


def run_30x50() -> dict:
    plan_id = "30x50-Model-landscape"
    pred = json.loads((PRED_DIR / f"{plan_id}.json").read_text(encoding="utf-8"))
    gt = json.loads((GT_DIR / f"{plan_id}.json").read_text(encoding="utf-8"))
    pw = {w["id"]: w for w in pred["walls"]}

    # Anchors, from out/pin_check_30x50-...png + the raw coordinate dump:
    # W13 (top wall, spans nearly the full pred bbox width) <-> w_s102
    # (top wall, GT's longest wall) -- unmistakable in the plot (top red
    # line spanning the full drawing). W36 (left wall, spans nearly the
    # full pred bbox height at the left edge) <-> w_s111 (left wall).
    # W19 (bottom wall, the longer of two near-duplicate bottom
    # detections W19/W42) <-> w_s110 (bottom wall). All three visually
    # confirmed against the plot: three long red lines at top, left, and
    # bottom of the pred cluster, matching the same three sides in GT.
    src = [
        tuple(pw["W13"]["start"]), tuple(pw["W13"]["end"]),  # top wall, left-to-right (x: 255.8 -> 1413.9)
        tuple(pw["W36"]["start"]), tuple(pw["W36"]["end"]),  # left wall, top-to-bottom (y: 247.6 -> 932.8)
        tuple(pw["W19"]["start"]), tuple(pw["W19"]["end"]),  # bottom wall, left-to-right (x: 255.7 -> 1425.4)
    ]
    dst = [
        (4116.6, 4085.3), (16912.8, 4059.2),  # w_s102 start/end (top, left-to-right)
        (4116.6, 4085.3), (4143.0, 11179.7),  # w_s111 end/start (left, top-to-bottom: y 4085.3 -> 11179.7)
        (4143.0, 11179.7), (13523.4, 11127.2),  # w_s110 end/start (bottom, left-to-right)
    ]
    transform = fit_similarity_umeyama(src, dst)
    residuals = fit_residuals(transform, src, dst)

    nominal_w, nominal_h = 30 * FT_TO_MM, 50 * FT_TO_MM
    gt_bbox_w = 16912.8 - 4116.6
    gt_bbox_h = 11179.7 - 4059.2
    pred_xs = [c for w in pred["walls"] for c in (w["start"][0], w["end"][0])]
    pred_ys = [c for w in pred["walls"] for c in (w["start"][1], w["end"][1])]
    pred_bbox_w_native = max(pred_xs) - min(pred_xs)
    pred_bbox_h_native = max(pred_ys) - min(pred_ys)
    pinned_implied_w = pred_bbox_w_native * transform.scale
    pinned_implied_h = pred_bbox_h_native * transform.scale

    return _finish(plan_id, pred, gt, transform, residuals, {
        "nominal_mm": [nominal_w, nominal_h],
        "gt_bbox_mm": [round(gt_bbox_w, 1), round(gt_bbox_h, 1)],
        "pred_bbox_native": [round(pred_bbox_w_native, 1), round(pred_bbox_h_native, 1)],
        "pinned_transform_implied_pred_envelope_mm": [round(pinned_implied_w, 1), round(pinned_implied_h, 1)],
    })


def _finish(plan_id, pred, gt, transform, residuals, scale_check) -> dict:
    aligned = apply_transform_to_plan(pred, transform)
    diagonal = plan_diagonal(gt["walls"])
    tau_1pct = 0.01 * diagonal

    per_gt_wall = []
    for gw in gt["walls"]:
        verdict = classify_gt_wall(gw, aligned["walls"], tau_1pct)
        verdict["gt_id"] = gw["id"]
        verdict["gt_length"] = round(
            ((gw["start"][0] - gw["end"][0]) ** 2 + (gw["start"][1] - gw["end"][1]) ** 2) ** 0.5, 1
        )
        per_gt_wall.append(verdict)

    counts = {"MATCHED": 0, "MISPLACED": 0, "FRAGMENTED": 0, "ABSENT": 0}
    for v in per_gt_wall:
        counts[v["verdict"]] += 1

    m = match_walls(aligned["walls"], gt["walls"], 0.01, diagonal)

    return {
        "plan_id": plan_id,
        "pinned_transform": {
            "scale": transform.scale,
            "rotation_deg": transform.rotation_deg,
            "tx": transform.tx,
            "ty": transform.ty,
        },
        "anchor_fit_residuals_native_to_gt_mm": [round(r, 1) for r in residuals],
        "scale_cross_check": scale_check,
        "n_gt_walls": len(gt["walls"]),
        "n_pred_walls": len(pred["walls"]),
        "per_gt_wall_verdict": per_gt_wall,
        "verdict_counts": counts,
        "hungarian_matched_at_1pct": len(m.pairs),
        "hungarian_precision_1pct": round(m.precision, 4),
        "hungarian_recall_1pct": round(m.recall, 4),
    }


def main() -> None:
    results = {"15x30-ft-Best-House-Plan-Model": run_15x30(), "30x50-Model-landscape": run_30x50()}
    OUT_PATH.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
