/**
 * Synthetic source assets for `ingest.test.ts` — no network, no licensing
 * question, deterministic. Not real catalog material; M3c picks a real source
 * the way `scripts/materials/curated.ts` picked ambientCG for floors.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import type { AssetSource } from "./types";

async function writeFlatPng(dst: string, w: number, h: number, rgb: [number, number, number]): Promise<void> {
  mkdirSync(path.dirname(dst), { recursive: true });
  const buf = Buffer.alloc(w * h * 3);
  for (let i = 0; i < w * h; i++) {
    buf[i * 3] = rgb[0];
    buf[i * 3 + 1] = rgb[1];
    buf[i * 3 + 2] = rgb[2];
  }
  await sharp(buf, { raw: { width: w, height: h, channels: 3 } }).png().toFile(dst);
}

/** A bright base colour with a near-black band across the top `darkFraction`
 *  of rows — a crude stand-in for a baked-shadow / baked-AO pass, which is
 *  exactly what §1.1's dark-pixel-fraction check exists to catch. */
async function writeAlbedoWithDarkBand(
  dst: string,
  w: number,
  h: number,
  brightRgb: [number, number, number],
  darkFraction: number,
): Promise<void> {
  mkdirSync(path.dirname(dst), { recursive: true });
  const darkRows = Math.round(h * darkFraction);
  const buf = Buffer.alloc(w * h * 3);
  for (let y = 0; y < h; y++) {
    const dark = y < darkRows;
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 3;
      if (dark) {
        buf[i] = 4;
        buf[i + 1] = 4;
        buf[i + 2] = 4;
      } else {
        buf[i] = brightRgb[0];
        buf[i + 1] = brightRgb[1];
        buf[i + 2] = brightRgb[2];
      }
    }
  }
  await sharp(buf, { raw: { width: w, height: h, channels: 3 } }).png().toFile(dst);
}

function writeDescriptor(dir: string, asset: AssetSource): void {
  writeFileSync(path.join(dir, "asset.json"), JSON.stringify(asset, null, 2));
}

export interface Fixtures {
  conformingDir: string;
  nonConformingDir: string;
}

export async function generateFixtures(rootDir: string): Promise<Fixtures> {
  const conformingDir = path.join(rootDir, "plaster-white-matte");
  await writeFlatPng(path.join(conformingDir, "albedo.png"), 1024, 1024, [230, 228, 222]); // linear ~0.79, matte-plaster band is [0.75,0.85]-ish reflectance per §1.1's reference table
  await writeFlatPng(path.join(conformingDir, "normal.png"), 1024, 1024, [128, 128, 255]); // flat tangent-space neutral
  writeDescriptor(conformingDir, {
    id: "plaster-white-matte",
    name: "White matte plaster",
    family: "plaster",
    class: "walls",
    surfaceClass: "matte-plaster",
    coverM: 2.0,
    roughnessScalar: 0.85,
    metalnessScalar: 0,
    license: "synthetic test fixture",
    source: "generated by scripts/materials/ingest/fixtures.ts",
    maps: { albedo: "albedo.png", normal: "normal.png" },
  });

  const nonConformingDir = path.join(rootDir, "baked-shadow-plaster");
  await writeAlbedoWithDarkBand(path.join(nonConformingDir, "albedo.png"), 1024, 1024, [230, 228, 222], 0.2);
  await writeFlatPng(path.join(nonConformingDir, "normal.png"), 1024, 1024, [128, 128, 255]);
  writeDescriptor(nonConformingDir, {
    id: "baked-shadow-plaster",
    name: "Plaster with baked shadow (deliberately non-conforming)",
    family: "plaster",
    class: "walls",
    surfaceClass: "matte-plaster",
    coverM: 2.0,
    roughnessScalar: 0.85,
    metalnessScalar: 0,
    license: "synthetic test fixture",
    source: "generated by scripts/materials/ingest/fixtures.ts",
    maps: { albedo: "albedo.png", normal: "normal.png" },
  });

  return { conformingDir, nonConformingDir };
}
