/**
 * Floor material registry — the catalog of image-based PBR floors.
 *
 * This module and its sibling loader own everything about real-texture floors:
 * the catalog, the caching, and the physical-scale maths. `src/viewport3d/
 * textures.ts` (a protected file) only needs to delegate to it, which keeps the
 * change to the guarded 3D layer down to a few lines.
 *
 * Generated by scripts/materials/* from ambientCG. Everything is CC0 public
 * domain — no attribution required, redistribution allowed. Provenance travels
 * with each entry anyway.
 */

import manifest from "../../data/materials-floors.manifest.json";

export type FloorFamily = "wood" | "tile" | "stone" | "carpet" | "concrete";

export interface FloorMaterial {
  /** Stable id, persisted in saved projects as `Room.floor`. */
  id: string;
  name: string;
  family: FloorFamily;
  /**
   * How many METRES one texture repeat spans in the real world.
   *
   * This is the field that decides whether a floor looks right. Wood and tile
   * carry it from ambientCG's published dimensions, so a 1.8 m oak tile lands
   * life-size; carpet, concrete and terrazzo are stochastic and use a curated
   * value, which is undetectable because they have no feature of known size.
   */
  coverM: number;
  /** Base roughness, used as a multiplier alongside the roughness map. */
  roughness: number;
  maps: { color: string; normal: string; roughness: string };
  thumb: string;
  license: string;
  source: string;
}

export const FLOOR_MATERIALS = manifest as FloorMaterial[];

const BY_ID = new Map(FLOOR_MATERIALS.map((m) => [m.id, m]));

export function getFloorMaterial(id: string): FloorMaterial | undefined {
  return BY_ID.get(id);
}

/**
 * The three original procedural styles, kept working forever.
 *
 * `Room.floor` is persisted, so every project saved before this catalog existed
 * holds one of these strings. They are NOT in the manifest and must keep
 * resolving to the canvas-drawn textures in textures.ts — otherwise opening an
 * old project shows an untextured floor.
 */
export const LEGACY_STYLES = new Set(["wood", "tile", "concrete"]);

export function isLegacyStyle(id: string): boolean {
  return LEGACY_STYLES.has(id);
}

/** Picker ordering: group by family, then by name within it. */
export const FAMILY_ORDER: FloorFamily[] = ["wood", "tile", "stone", "concrete", "carpet"];

export const FAMILY_LABEL: Record<FloorFamily, string> = {
  wood: "Wood",
  tile: "Tile",
  stone: "Stone",
  concrete: "Concrete",
  carpet: "Carpet",
};
